#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
server:
  port: 8080
spring:
  application:
    name: ${artifactId}
  profiles:
    active: dev
endpoints:
  shutdown:
    enabled: true
    sensitive: false
management:
  security:
    enabled: false

